OPTION(CURL_IS_STATIC "on if curl is a static lib " ON)
MARK_AS_ADVANCED(CURL_IS_STATIC)

IF(ZLIB_FOUND)
    ADD_DEFINITIONS(-DUSE_ZLIB)
ENDIF()


SET(TARGET_SRC
    ReaderWriterCURL.cpp
)

SET(TARGET_H
    ReaderWriterCURL.h
)

OSG_ADD_PACKAGE_DEPENDENCY(CURL)
IF(ZLIB_FOUND)
    SET(TARGET_EXTERNAL_LIBRARIES CURL::libcurl ZLIB::ZLIB)
    OSG_ADD_PACKAGE_DEPENDENCY(ZLIB)
ELSE()
    SET(TARGET_EXTERNAL_LIBRARIES CURL::libcurl)
ENDIF()

IF(WIN32 OR MINGW)
    IF(CURL_IS_STATIC)
        ADD_DEFINITIONS(-DCURL_STATICLIB)
        SET(TARGET_EXTERNAL_LIBRARIES ${TARGET_EXTERNAL_LIBRARIES} ws2_32 winmm wldap32)
    ENDIF()
ENDIF()

#### end var setup  ###
SETUP_PLUGIN(curl)
